name: My First Workflow

on:
  push:
  pull_request:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

      - name: Print message
        run: echo "Hello, GitHub Actions!"

      - name: Print my name
        run: echo "xyz"

  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Goodbye from second job"
        